// CFOP mais comuns
export const CFOP = {
  VENDA_ESTADUAL_REVENDA: '5102',
  VENDA_INTERESTADUAL_REVENDA: '6102',
  VENDA_ESTADUAL_PRODUCAO: '5101',
  VENDA_INTERESTADUAL_PRODUCAO: '6101',
  DEVOLUCAO_COMPRA_ESTADUAL: '5202',
  DEVOLUCAO_COMPRA_INTERESTADUAL: '6202',
  DEVOLUCAO_VENDA_ESTADUAL: '1202',
  DEVOLUCAO_VENDA_INTERESTADUAL: '2202',
  TRANSFERENCIA_ESTADUAL: '5152',
  TRANSFERENCIA_INTERESTADUAL: '6152',
  PRESTACAO_SERVICO: '5933',
} as const;

// CSOSN (Simples Nacional)
export const CSOSN = {
  TRIBUTADA_SEM_CREDITO: '102',
  TRIBUTADA_COM_ST: '202',
  NAO_TRIBUTADA: '400',
  JA_TRIBUTADA_ST: '500',
  OUTROS: '900',
} as const;

// Alíquotas Lucro Presumido (basis points)
export const ALIQUOTAS_LP = {
  PIS: 65,       // 0,65%
  COFINS: 300,   // 3,00%
  IRPJ: 1500,    // 15%
  CSLL: 900,     // 9%
} as const;

export const VERSAO_LAYOUT_SPED = '017' as const;
